language: node_js
node_js:
  - "6"
branches:
  only:
  - master
before_install:
- git config --global user.name 'laosb'
- git config --global user.email laosb@lasteam.net
install:
- git submodule update --init
- npm install hexo-cli -g
- (cd site && npm install)
script:
- (cd site && hexo clean)
- (cd site && hexo g)
- (cd site && hexo d)
cache:
  directories:
    - site/node_modules
